server:
  port: 8761

spring:
  application:
    name: discoveryservice          # MSA 에 고유한 ID를 부여해야 하는데, 그 역할로 application name이 들어감.

eureka:
  client:
    register-with-eureka: false     # 기본 값(true) : 이 애플리케이션이 Eureka 서버에 자신을 등록할지 여부
    fetch-registry: false           # 기본 값(true) : Eureka 서버로부터 등록된 서비스 목록을 받아올지 여부
