server:
  port: 8761

spring:
  application:
    name: discoveryservice          # MSA ?? ???? ???? ?? ?? ID? ???

eureka:
  client:
    register-with-eureka: false     # ???(true) : ? ??????? Eureka ??? ??? ????? ?? ??
    fetch-registry: false           # ???(true) : Eureka ????? ??? ??? ??? ????? ?? ??
